# Generated by Django 4.1.7 on 2023-03-20 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jop', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Title',
            new_name='jop',
        ),
    ]
