# Generated by Django 4.1.7 on 2023-03-21 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jop', '0002_rename_title_jop'),
    ]

    operations = [
        migrations.AddField(
            model_name='jop',
            name='description',
            field=models.TextField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jop',
            name='experience',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='jop',
            name='jop_title',
            field=models.CharField(choices=[('Full_time', 'Full_time'), ('Part_time', 'Part_time')], default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jop',
            name='published_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='jop',
            name='salary',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jop',
            name='vacancy',
            field=models.IntegerField(default=1),
        ),
    ]
