# Generated by Django 4.1.7 on 2023-03-26 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jop', '0005_jop_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='jop',
            name='image',
            field=models.ImageField(default='', upload_to='photos/y/m/d'),
            preserve_default=False,
        ),
    ]
